### ISSUE TITLE
This invite link is no longer active.

### ISSUE THREAD

**Issue by ZirconfleX** [MakeInBelgium/coronadenktank#14]
Hallo,

Deze link werkt niet en geeft de boodschap uit de titel.
"Chatten met andere makers: Slack "

Cheers

**Comment by driesvints** [comment]
@ZirconfleX denk dat de link nu wel terug werkt. 

<img width="726" alt="Screenshot 2020-03-28 at 12 45 33" src="https://user-images.githubusercontent.com/594614/77822347-09fa0c00-70f2-11ea-9865-2e030a03f163.png">

**Comment by ZirconfleX** [comment]
Beste Dries,

Inderdaad het werkt weer :-)

Groeten,

Marc
